### ISSUE TITLE
Bad rule set highlight while hovering

### ISSUE THREAD

**Issue by qligier** [standardhealth/vscode-language-fsh#50]
If a rule set has a dash in its name, the name highlighting breaks while hovering with the CTRL-key hold.

![Untitled](https://user-images.githubusercontent.com/3299399/199493266-0d9970f9-7d2e-4ed1-aa22-1855c5be4bf0.png)

Note that if I click, it brings me to the right definition, it's only a cosmetic issue.

**Comment by jafeltra** [comment]
In a recent version of the extension, the highlighting was updated. It looks like ia rule set with a dash in the name is working correctly with those changes now: 

![image](https://github.com/user-attachments/assets/b0a41f4a-1394-441a-b8dd-a0250e260753)

I'm going to close this since it not longer seems to be an issue, but if it still does not work for you, feel free to comment on this issue.
